def decrypt(msg):
    decryption_key = {
        '!': 'a',
        ')': 'b',
        '"': 'c',
        '(': 'd',
        '£': 'e',
        '*': 'f',
        '%': 'g',
        '&': 'h',
        '>': 'i',
        '<': 'j',
        '@': 'k',
        'a': 'l',
        'b': 'm',
        'c': 'n',
        'd': 'o',
        'e': 'p',
        'f': 'q',
        'g': 'r',
        'h': 's',
        'i': 't',
        'j': 'u',
        'k': 'v',
        'l': 'w',
        'm': 'x',
        'n': 'y',
        'o': 'z',
        ' ': ' ',
    }

    return ''.join(map(lambda s: decryption_key[s], msg))
